<?php
$data = array (
  0 => 
  array (
    'cat_id' => '161',
    'cat_name' => '酒吧',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '162',
    'cat_name' => 'KTV',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '163',
    'cat_name' => '名仕酒吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  3 => 
  array (
    'cat_id' => '164',
    'cat_name' => '空间派对',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '165',
    'cat_name' => '1919音乐吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '166',
    'cat_name' => '空瓶子酒吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '167',
    'cat_name' => '基地露天酒吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '168',
    'cat_name' => '鼎极酒吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '169',
    'cat_name' => 'M2',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '191',
    'cat_name' => 'A+酒吧',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  10 => 
  array (
    'cat_id' => '170',
    'cat_name' => '欢乐世界',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '171',
    'cat_name' => '伊贝莎',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  12 => 
  array (
    'cat_id' => '172',
    'cat_name' => '沸点',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  13 => 
  array (
    'cat_id' => '178',
    'cat_name' => '快乐畅响',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  14 => 
  array (
    'cat_id' => '181',
    'cat_name' => '麦乐狂唱',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  15 => 
  array (
    'cat_id' => '188',
    'cat_name' => '飞越时空',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  16 => 
  array (
    'cat_id' => '189',
    'cat_name' => '海陆会',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>